### ISSUE TITLE
Using path-to-regexp?

### ISSUE THREAD

**Issue by sudo-sand** [rawnly/next-middleware-pahthandler#1]
You mentioned using path-to-regexp to be more dynamic

How?

I want to use it to match /en/dashboard and /es/dashboard

**Comment by rawnly** [comment]
You can see my implementation in the original discussion in the nextjs repo, the only con is that you can't use a map anymore since the regex has to be tested

**Comment by rawnly** [comment]
You might want to have a look at https://github.com/Rawnly/next-wayfinder. I moved this project into a separate package since seems that it can be useful to some users. (not yet published) tomorrow I'll polish and publish it :)

**Comment by sudo-sand** [comment]
That's cool!

**Comment by rawnly** [comment]
@sudo-sand just published as `next-wayfinder` :)
